### PR TITLE
Libvirt

### PR DESCRIPTION
**Pull request by ezr-ondrej**

### CODE REVIEW

**Comment by jyejare** [comment]
Looks Good :+1:

**Comment by jyejare** [comment]
@ezr-ondrej  I tested this today, I found below issues :

1. theforeman.foreman module installation issue.
```
ERROR! couldn't resolve module/action 'theforeman.foreman.foreman_organization'. This often indicates a misspelling, missing collection, or incorrect module path.
```

2. The package dependency error which was causing due to existing rhel7 repository on satellite VM.
```
http://pastebin.test.redhat.com/842132
```

**Comment by parthaa** [comment]
Hmm that should be in your `Summit-2020_Summit-Contents_Satellite_6_7_RHEL7` repo

**Comment by parthaa** [comment]
hmm that has `tfm-rubygem-ruby-libvirt-0.7.0-4.el7sat.x86_64` though. Ok we need to disable epel  since its pulling the wrong version. Epel gets pulled in from the `rhel7_repo_path:` setting. May be we can add something in the pre-software.yml to disable it before sat install?

**Comment by parthaa** [comment]
It gets added here  https://github.com/ezr-ondrej/agnosticd/blob/satellite_lab/ansible/configs/satellite-vm/files/repos_template.j2#L1-L11 

just remove or comment out those lines and try again

**Comment by parthaa** [comment]
you can also add something like
```
- yum_repository:
    name: epel
    enabled: false
    state: update
```

**Comment by parthaa** [comment]
ACK works well

**Comment by ezr-ondrej** [comment]
Ok, thanks @parthaa, I'll go ahead and merge :)

**Pull request merged**
